---
- hosts: all
  tasks:
  - name: Create a group of all hosts by operating system
    action: group_by key={{ansible_distribution}}-{{ansible_distribution_version}}


- hosts: bacula-client
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - client
  vars:
        client_name: client
        bacula_fd_port: 9666
        dir_name: client-dir
        dir_fd_password: sdfkjasldkfja
        client_password: sdfkjasldkfja
