---
- hosts: all
  tasks:
  - name: Create a group of all hosts by operating system
    action: group_by key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: bacula-server
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - dir-client
    - director
  vars:
    pgsql_password: sdfsdfasd
    dir_fd_name: directory
    bacula_fd_port: 9102
    bacula_dir_port: 9667
    dir_name: client-dir
    dir_fd_password: sdfkjasldkfja
    client_password: sdfkjasldkfja
    bconsole_password: sdfasdfasdfa
    bacula_sd_port: 9668
    sd_password: alalalala
    mail: simarg@gmail.com
    pg_hba_conf: /etc/postgresql/9.1/main/pg_hba.conf
    backup_dir: /var/backups

- hosts: bacula-server
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - storage
  vars:
    bacula_sd_port: 9668
    sd_name: sdname
    dir_name: client-dir
    sd_password: alalalala
    backup_dir: /var/backups

- hosts: bacula-server
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - almir
