---
- hosts: testing-storage
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - storage

- hosts: testing-client
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - client

- hosts: testing-director
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - director

- hosts: testing-almir
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - almir
