---
- hosts: all
  tasks:
  - name: Create a group of all hosts by operating system
    action: group_by key={{ansible_distribution}}-{{ansible_distribution_version}}


- hosts: bacula-client
  vars_files:
    - var
  sudo: yes
  roles:
    - common
    - client
  vars:
        client_name: client
        client_ip: 192.168.33.10
        client_port: 9102
        client_include_dirs: /etc
        client_exclude_dirs: nope
        bacula_fd_port: 9102
        dir_name: client-dir
        dir_fd_password: sdfkjasldkfja
        client_password: sdfkjasldkfja
