- action: apt pkg=$item update_cache=yes cache_valid_time=180 
  with_items: 
    - postgresql-client
    - postgresql
    - python-psycopg2


- apt: pkg={{ item }}
  with_items: 
    - bacula-director-pgsql
    - bacula-console

- service: name=bacula-director state=stopped

- template: src=bacula-dir.conf.jinja2 dest=/etc/bacula/bacula-dir.conf backup=yes

- template: src=bconsole.conf.jinja2 dest=/etc/bacula/bconsole.conf backup=yes

###
# Copy pools
###

- copy: src=pool_defaults.conf dest=/etc/bacula/

- copy: src=pool_diff_defaults.conf dest=/etc/bacula/

- copy: src=pool_full_defaults.conf dest=/etc/bacula/

- copy: src=pool_inc_defaults.conf dest=/etc/bacula/

###
#fix for postgres sudo
- copy: src=vagrant dest=/etc/sudoers.d mode=440  owner=root group=root

###

- file: path=/etc/bacula/clients state=directory

- command: touch /etc/bacula/clients/dummy.conf
## load a clients
- copy: src={{ item }} dest=/etc/bacula/clients/ owner=root
#not sure really that is a trouble with fileglob or my path
  with_fileglob:
      - /Users/kevit/Projects/ansible-bacula/clients/*

- postgresql_user: user=bacula password={{ pgsql_password }}:w
  sudo_user: postgres

# dbcheck 
# http://www.bacula.org/manuals/en/utility/utility/Volume_Utility_Tools.html#SECTION002120000000000000000
# Usage: dbcheck [-c config ] [-B] [-C catalog name] [-d debug_level] 
# <working-directory> <bacula-database> <user> <password> [<dbhost>] [<dbport>]
# Used for default client cleaning
# TODO: needs a dbdump just to be sure
- lineinfile: dest=$pg_hba_conf regexp="^host\s+all\s+bacula\s+127\.0\.0\.1/32\s+trust$" insertafter="^#\sIPv4\slocal.+" line="host    all             bacula  127.0.0.1/32            trust"
- name: Reload PostgreSQL if permissions have changed.
  service: name=postgresql state=reloaded

- command: dbcheck . bacula bacula {{ pgsql_password }} localhost -bf


- file: path={{ backup_dir }} state=directory owner=bacula group=tape


- service: name=bacula-director state=started
