- action: apt pkg=$item update_cache=yes cache_valid_time=180 
  with_items: 
    - postgresql-client
    - postgresql
    - python-psycopg2


- apt: pkg={{ item }}
  with_items: 
    - bacula-director-pgsql
    - bacula-console

- service: name=bacula-director state=stopped

- template: src=bacula-dir.conf.jinja2 dest=/etc/bacula/bacula-dir.conf backup=yes

- template: src=bconsole.conf.jinja2 dest=/etc/bacula/bconsole.conf backup=yes

###
# Copy pools
###

- copy: src=pool_defaults.conf dest=/etc/bacula/

- copy: src=pool_diff_defaults.conf dest=/etc/bacula/

- copy: src=pool_full_defaults.conf dest=/etc/bacula/

- copy: src=pool_inc_defaults.conf dest=/etc/bacula/

###

- file: path=/etc/bacula/clients state=directory

- command: touch /etc/bacula/clients/dummy.conf

- postgresql_user: user=bacula password={{ pgsql_password }}:w
  sudo_user: postgres

# dbcheck 
# http://www.bacula.org/manuals/en/utility/utility/Volume_Utility_Tools.html#SECTION002120000000000000000
# Usage: dbcheck [-c config ] [-B] [-C catalog name] [-d debug_level] 
# <working-directory> <bacula-database> <user> <password> [<dbhost>] [<dbport>]
# Used for default client cleaning
# TODO: needs a dbdump just to be sure
- command: dbcheck . bacula bacula {{ pgsql_password }} localhost -bf


- file: path={{ backup_dir }} state=directory owner=bacula group=tape


- service: name=bacula-director state=started
