---
- apt: pkg={{ item }} update_cache=yes cache_valid_time=180
  with_items: 
    - bacula-fd

- service: name=bacula-fd state=stopped

- template: src=bacula-fd.conf.jinja2 dest=/etc/bacula/bacula-fd.conf backup=yes
- action: file path=/etc/bacula/clients state=directory


- service: name=bacula-fd state=started
#- template: src=client.conf.jinja2 dest=clients/{{ client_name }}-client.conf
- local_action: template src=client.conf.jinja2 dest=clients/{{ client_name }}-client.conf
  sudo: no
#  notify:
#  - restart bacula-dir
